name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn
      run: npm install -g yarn lerna
    - name: yarn bootstrap
      run: yarn bootstrap
    - name: yarn build
      run: yarn build
    - name: yarn lint
      run: yarn lint
    - name: yarn test
      run: yarn test
